version: '2'

services:
  base-consul:
    build:
      context: .
    ports:
      - "8300:8300"       # server RPC
      - "8301:8301"       # serf LAN
      - "8301:8301/udp"   # serf LAN (UDP)
      - "8302:8302"       # serf WAN
      - "8302:8302/udp"   # serf WAN (UDP)
      - "8500:8500"       # HTTP
      - "8501:8501"       # HTTPS
      - "8600:8600"       # DNS
      - "8600:8600/udp"   # DNS (UDP)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /host/data:/var/consul                                           # volume for data
    environment:
      - CONSUL_VERSION=${CONSUL_VERSION}
      - CONSULUI_VERSION=${CONSULUI_VERSION}
      - CONSULTEMPLATE_VERSION=${CONSULTEMPLATE_VERSION}
      - RUBY_VERSION=${RUBY_VERSION}
      - CONSUL_OPTIONS=${CONSUL_OPTIONS}                                  # minimal server options
      - CONSUL_DATACENTER=local                                           # datacenter
      - CONSUL_DOMAIN=test                                                # domain name
      - CONSUL_ENCRYPT=h2N6R1eyTysjBzzXxAWJvA==                           # encryption key
      - CONSUL_TLS=1                                                      # enable TLS
      - CONSUL_TLSCAFILE=/etc/consul.d/ssl/ca.pem                         # TLS CA certificate file
      - CONSUL_TLSCERTFILE=/etc/consul.d/ssl/server.pem                   # TLS server certificate file
      - CONSUL_TLSKEYFILE=/etc/consul.d/ssl/server-priv-key.pem           # TLS server certificate key file
      - CONSUL_ACLDATACENTER=local                                        # ACL authoritative datacenter (server only)
      - CONSUL_ACLMASTERTOKEN=a29fc95f-2501-4fd1-902c-686151082fe9        # ACL master token (server only)
      - CONSUL_ACLDEFAULTPOLICY=deny                                      # ACL default policy (server only)
      #- CONSUL_ACLDOWNPOLICY=extend-cache                                # ACL down policy (server only)
      #- CONSUL_ACLTTL=30                                                 # ACL TTL (server only)
      #- CONSUL_ACLTOKEN=d17fade7-2391-45a4-aa00-c9ed5e707e0b             # ACL token (client only)
      #- CONSUL_RAFTMULTIPLIER=0                                          # Raft mutliplier
